services:
  indexer-db:
    profiles: [scaling]
    container_name: ${COMPOSE_PROJECT_NAME}-indexer-db
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - indexer_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "--host", "localhost", "-proot"]
      timeout: 20s
      retries: 10

  indexer:
    profiles: [scaling]
    container_name: ${COMPOSE_PROJECT_NAME}-indexer
    image: ghcr.io/flare-foundation/flare-system-c-chain-indexer:latest
    volumes:
      - ./mounts/indexer/config.toml:/app/config.toml
    restart: unless-stopped
    depends_on:
      indexer-db:
        condition: service_healthy

  # feed-value-provider:
  #   profiles: [scaling]
  #   container_name: ${COMPOSE_PROJECT_NAME}-feed-value-provider
  #   image: ghcr.io/flare-foundation/ftso-scaling:latest
  #   env_file:
  #     - ./mounts/scaling/.env
  #   command: "node dist/apps/example_provider/apps/example_provider/src/main.js"
  #   ports:
  #     - "3101:3101"
  #   depends_on:
  #     - indexer

  feed-value-provider:
    profiles: [scaling]
    container_name: ${COMPOSE_PROJECT_NAME}-feed-value-provider
    image: ghcr.io/flare-foundation/ftso-v2-example-value-provider:latest
    environment:
      VALUE_PROVIDER_IMPL: "fixed"
    ports:
      - "3101:3101"
    depends_on:
      - indexer

  data-provider:
    profiles: [scaling]
    container_name: ${COMPOSE_PROJECT_NAME}-data-provider
    image: ghcr.io/flare-foundation/ftso-scaling:latest
    env_file:
      - ./mounts/scaling/.env
    command: "node dist/apps/ftso-data-provider/apps/ftso-data-provider/src/main.js"
    stop_grace_period: 135s # Voting round 90s + reveal deadline 45s
    depends_on:
      # - indexer
      - feed-value-provider

  client:
    profiles: [scaling]
    container_name: ${COMPOSE_PROJECT_NAME}-client
    image: ghcr.io/flare-foundation/flare-system-client:latest
    volumes:
      - ./mounts/client/config.toml:/app/config.toml
    environment:
      SYSTEM_CLIENT_SENDER_PRIVATE_KEY: ${SIGNING_PK}
      SIGNING_POLICY_PRIVATE_KEY: ${SIGNING_PK}
      PROTOCOL_MANAGER_SUBMIT_PRIVATE_KEY: ${SUBMIT_PK}
      PROTOCOL_MANAGER_SUBMIT_SIGNATURES_PRIVATE_KEY: ${SIGNATURES_PK}
      PROTOCOL_X_API_KEY_100: "abcdef"
    stop_grace_period: 135s # Voting round 90s + reveal deadline 45s
    depends_on:
      - data-provider
      - indexer

  fast-updates:
    profiles: [fast-updates]
    container_name: ${COMPOSE_PROJECT_NAME}-fast-updates
    image: ghcr.io/flare-foundation/fast-updates/go-client:latest
    volumes:
      - ./mounts/fast-updates/config.toml:/app/config.toml
    environment:
      SIGNING_PRIVATE_KEY: ${SIGNING_PK}
      ACCOUNTS: ${FAST_UPDATES_ACCOUNTS}
      SORTITION_PRIVATE_KEY: ${FAST_UPDATES_SORTITION_PRIVATE_KEY}
    depends_on:
      - indexer

volumes:
  indexer_data:
